import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// const sidebars: SidebarsConfig = {
//   solidity: [
//     'solidity/introduction',
//     {
//       label: 'Solidity',
//       type: 'category',
//       link: { type: 'generated-index' },
//       items: [
//         {
//           type: 'autogenerated',
//           dirName: 'solidity',
//         },
//       ],
//     },
//   ],
//   tools: [
//     'tools/introduction',
//     'tools/everything-quick-search-local-files',
//     'tools/wappalyzer-recognize-technology',
//     'tools/windows-custom-right-click-menu',
//     'tools/vscode-config',
//     'tools/idea-config',
//     'tools/vite-plugin',
//     'tools/jetbrains-product-activation-method',
//   ],
// }
const sidebars: SidebarsConfig = {
  // key 对应顶部栏，顶部栏会在下面讲到
  Solidity: [
    'solidity/introduction',
    { 
      type: "autogenerated", 
      dirName: 'solidity', 
      
    }
  ],
  Security: [{ type: "autogenerated", dirName: 'security', }],
  Web3Tools: [{ type: "autogenerated", dirName: 'Web3tools', }],
  CTF: [{ type: "autogenerated", dirName: 'ctf', }],
  Recurrence: [{ type: "autogenerated", dirName: 'recurrence', }],
};

module.exports = sidebars
